### PR TITLE
Add tinfo to ncurses dependencies

### PR DESCRIPTION
**Pull request by ghost**
In some Linux configurations, ncurses.so does not refer to tinfo.so,
in which case -ltinfo has to be explicitly passed to the linker.

Please merge.
Thanks.

### CODE REVIEW

**Comment by matszpk** [comment]
Because some other Linux doesn't have pkg config info about ncurses thus I added manually tinfo to dependencies.

**Comment by ghost** [comment]
Please note that open source development is also about tracking contributions made by concrete developers. Copying an idea from a pull request and not mentioning the developer who contributed the idea is ***stealing***. I demand that you create another commit which will mention the developer who contributed the ***idea*** to your software. Thanks.

**Comment by matszpk** [comment]
Your last comment in big letters is obsolete. Maybe, I just will add your to contributors later. After some reconsiderations and problem researching I just solved issue in another way. I treated your pull request as an issue signaling. Please do not spam my project by adding obsolete comments. Your pull request is too small to treat as any important idea - please reconsider your conversation.

**Comment by ghost** [comment]
I don't understand why the comment would be obsolete.

You added your own name to small commits such as 0ac9d39a696a04c21a389bebf3200fba2374dc88 "Add .gitignore" which added 3 lines of text to the repository. Why didn't you post this small commit anonymously, since it is small and does not carry any fundamental ideas?

**You aren't treating other people's small contributions in the same way as your own small contributions.**

Please reconsider your behavior.

Thanks.

----

adjective: obsolete
no longer produced or used; out of date.
"the disposal of old and obsolete machinery"
 
verb: obsolete
cause (a product or idea) to become obsolete by replacing it with something new.
"we're trying to stimulate the business by obsoleting last year's designs"

**Comment by matszpk** [comment]
Firstly: your version of the contribution has been rejected because I found other problems with your changes in other Linux distros, so I decided to resolve your problem in different way. I expected that you will confirm that problem has been resolved.
Please understand: I am not obligated to accept every contribution. Your contribution has been rejected due to technical problems in other Linux distros - that is all. I appreciate your engagement.  This is my choice. Maybe later I will add some file with list of contributors.

**Comment by ghost** [comment]
No, it hasn't been rejected - it has been **superseded**. It it would have been rejected, you wouldn't be building your own commit **on top of** the idea in the pull request.

I believe that the best course of action would have been to merge the pull request as it is and then to create a new commit changing the `pkg-config` line to `-ltinfo`.

In any case, you are free to cherry pick the commit from my fork of your repository. Thanks.

**Comment by matszpk** [comment]
Thank you for explanation. However for me, no sensible reasons to create new commit after accepting your contribution. I just resolved your problem in other way - that's all. Ofcourse, you can make your own fork with your solution. I would like to close this idle discussion about that issue.
Thanks.

**Comment by ghost** [comment]
True. But your repository has a greater momentum than mine because it has 164 github stars while mine is new and has 0 stars. It sometimes happens that a forked repository is more successful than the original one, but such cases are rare unless the original repository is no longer being maintained.

I think we can close this discussion. Enough has been written. Goodbye.

**Pull request closed without merging**
